services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: short-url-db-dev
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    volumes:
      - ./:/node/app/
    depends_on:
      - db
    command: sh -c "yarn start:dev"

volumes:
  db_data:
